backend:
  name: github
  repo: taoguangc/emptyarea

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: 'index'
    path: '{{path}}/index'
    fields:
      - { name: path, label: "路径" }
      - { name: date, label: "日期", widget: date }
      - { name: title, label: "标题" }
      - { name: description, label: "描述", required: false }
      - { name: body, label: Body, widget: markdown }
